/**
 * Deterministic stand-ins for the AI host, used by tests only. They exercise the real contracts; they
 * are not a model and prove nothing about semantic quality.
 */

export function fakeEnrichment(prepared: {
  source_ref: { id: string; version: number; input_digest: string };
  text: string;
  total_chars: number;
  provided_chars: number;
}) {
  const firstLine = prepared.text.split("\n")[0]?.trim() ?? "";
  const words = [...new Set(prepared.text.toLowerCase().match(/[\p{L}\p{N}]{3,}/gu) ?? [])].slice(0, 8);
  return {
    source_ref: prepared.source_ref,
    title: firstLine.slice(0, 60) || "Untitled",
    abstract: prepared.text.slice(0, 200).trim() || "Empty",
    terms: words,
    coverage: { read_chars: prepared.provided_chars, total_chars: prepared.total_chars },
  };
}

export function fakeArtifact(
  evidence: { id: string; request: string; items: { handle: string; excerpt: string | null }[] },
  title: string,
) {
  const bullets = evidence.items.map(
    (item) => `- ${(item.excerpt ?? "").replace(/\s+/g, " ").slice(0, 80)} [@${item.handle}]`,
  );
  return {
    evidence_run_id: evidence.id,
    intent: "review" as const,
    title,
    request: evidence.request,
    markdown: `## Records\n\n${bullets.join("\n")}\n`,
    limitations: ["Generated by a deterministic test agent."],
  };
}
